version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "5173:80" # host:container
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
