version: "3.9"

services:
  backend:
    build: ./backend
    image: anubhavpradhan/demoapp:backend
    container_name: backend-service
    ports:
      - "${BACKEND_PORT:-4000}:4000"   # host:container
    env_file:
      - ./backend/.env
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:4000}
    image: anubhavpradhan/demoapp:frontend
    container_name: frontend-service
    ports:
      - "${FRONTEND_PORT:-5173}:80"   # host:container
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet: {}
